In [1]:
from keras.models import load_model
import numpy as np
import librosa
import os
import json
        


In [2]:
# Load the saved model
model = load_model('/home/lab/SP-testing/Machine Learning Model/CNN/CNN.h5')

with open('model_and_classes.json', 'r') as json_file:
    class_label_mapping = json.load(json_file)

# Specify the path to the WAV file for prediction
directory_path = '/home/lab/SP-testing/Machine Learning Model/CNN/Outtest/'





2023-10-17 15:13:13.707405: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-10-17 15:13:13.713027: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-10-17 15:13:13.713239: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-10-17 15:13:13.713888: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

In [3]:
for filename in os.listdir(directory_path):
    if filename.endswith('.wav'):  # Make sure the file is a WAV file
        file_path = os.path.join(directory_path, filename)
        
        # Load and preprocess the audio data
        y, sr = librosa.load(file_path, sr=None)
        y = y.reshape(1, -1)
        
        # Perform the prediction
        predictions = model.predict(y)  # Assuming the model expects batches of data
        print(np.max(predictions))
        print(predictions)
        # Get the predicted class index
        predicted_class_index = np.argmax(predictions)
        
        # Map the predicted numerical label to the corresponding class name using the class label mapping
        predicted_class_name = None
        for class_name, label in class_label_mapping.items():
            if label == predicted_class_index:
                predicted_class_name = class_name
                break
        
        print(f"File: {filename}, Predicted class: {predicted_class_name}")

2023-10-17 15:13:16.995696: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8100
2023-10-17 15:13:17.722416: W tensorflow/stream_executor/gpu/asm_compiler.cc:230] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.9
2023-10-17 15:13:17.722435: W tensorflow/stream_executor/gpu/asm_compiler.cc:233] Used ptxas at ptxas
2023-10-17 15:13:17.722514: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] UNIMPLEMENTED: ptxas ptxas too old. Falling back to the driver to compile.
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.


1/1 [==============================] - 2s 2s/step
1.0
[[2.052386e-35 1.000000e+00]]
File: processed_HackRF-20230914_192128-433_021MHz-2MSps-2MHz.wav, Predicted class: True Signal
1/1 [==============================] - 0s 14ms/step
1.0
[[1.3727398e-34 1.0000000e+00]]
File: processed_HackRF-20230914_191457-433_021MHz-2MSps-2MHz.wav, Predicted class: True Signal
1/1 [==============================] - 0s 14ms/step
1.0
[[5.4454047e-35 1.0000000e+00]]
File: processed_HackRF-20230914_191731-433_021MHz-2MSps-2MHz.wav, Predicted class: True Signal
1/1 [==============================] - 0s 13ms/step


2023-10-17 15:13:18.276754: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


1.0
[[1.2742735e-34 1.0000000e+00]]
File: processed_HackRF-20230914_191223-433_021MHz-2MSps-2MHz.wav, Predicted class: True Signal
1/1 [==============================] - 0s 14ms/step
1.0
[[2.0265877e-35 1.0000000e+00]]
File: processed_HackRF-20230914_192140-433_021MHz-2MSps-2MHz.wav, Predicted class: True Signal
1/1 [==============================] - 0s 14ms/step
1.0
[[7.763136e-35 1.000000e+00]]
File: processed_HackRF-20230914_191556-433_021MHz-2MSps-2MHz.wav, Predicted class: True Signal
1/1 [==============================] - 0s 15ms/step
1.0
[[9.16789e-35 1.00000e+00]]
File: processed_HackRF-20230914_191358-433_021MHz-2MSps-2MHz.wav, Predicted class: True Signal
1/1 [==============================] - 0s 15ms/step
1.0
[[5.375685e-35 1.000000e+00]]
File: processed_HackRF-20230914_191656-433_021MHz-2MSps-2MHz.wav, Predicted class: True Signal
1/1 [==============================] - 0s 14ms/step
1.0
[[7.010413e-35 1.000000e+00]]
File: processed_HackRF-20230914_191521-433_021MHz-2MSps-2MH